### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ac1e28e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ac1e28e with merge ac1e28e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/nrf51-memory-map/builds/185929206)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 071901a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 071901a with merge 071901a...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/nrf51-memory-map/builds/185930770)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 34b4563 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 34b4563 with merge 34b4563...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nrf51-memory-map/builds/185931931)
Approved by: japaric
Pushing 34b4563c2a6ab32c1a54d848ffe0357c04cead42 to master...

**Pull request merged**
